package reciter.database.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTyped;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperFieldModel.DynamoDBAttributeType;
import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * @author szd2013
 * This contains different gender probability list attributed from different sources
 */
@DynamoDBTable(tableName = "Gender")
@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBDocument
public class Gender {
	
	@DynamoDBHashKey(attributeName = "uniqueId")
	@DynamoDBAutoGeneratedKey
	private String uniqueId;
	
	/**
	 * Name of the person, usually first name. <i>e.g. <b>Aban, Paul, Nancy </b></i>
	 */
	@JsonProperty(value = "name")
	@DynamoDBAttribute(attributeName = "name")
	private String name;
	/**
	 * Gender of the person
	 */
	@DynamoDBTyped(DynamoDBAttributeType.S)
	@JsonProperty(value = "gender")
	@DynamoDBAttribute(attributeName = "gender")
	private GenderEnum gender;
	/**
	 * The probability of the person to be male for female. <i>e.g. <b>"probability": 0.998814604077762</b></i>
	 */
	@JsonProperty(value = "probability")
	@DynamoDBAttribute(attributeName = "probability")
	private double probability;
}
